# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-2019

variables:
- group: JsonVariableGrp
- name: buildConfiguration
  value: 'Release'
- name: MailSettings.EMail
  value: '$(EMail)'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "Print EMail value"
      echo "Value: $(EMail)"

- task: FileTransform@1
  displayName: "Running File Transform Task"
  inputs:
    folderPath: 'DemoCoreApp/**/'
    fileType: 'json'
    targetFiles: '*.json'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Running Publish Artifacts'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishPipelineArtifact@1
  displayName: 'Uploading Artifact to Dir'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'artifactDrop'
    publishLocation: 'pipeline'
